### PR TITLE
Change Switch to Native

### PR DESCRIPTION
**Pull request by ttawan**
Not sure why you need custom view for Switch in React-native.

Problem: The Switch Image caused faded animation while toggling/switching (bad UX/UI)
Solution: Use native

They are have a native one to use. 
Reference:
https://facebook.github.io/react-native/docs/switch.html

Preview after changed
https://media.giphy.com/media/3o7WIObiTq1P19tZCg/giphy.gif

### CODE REVIEW

**Comment by trunghm** [comment]
Hi Tim,

It's good to know. Can you check if that component is compatible for Android too?

Thanks,
Trung

**Comment by ttawan** [comment]
@trunghm
It's suppose to work for both os. 

[https://www.safaribooksonline.com/library/view/learning-react-native/9781491929049/assets/lnrn_0412.png](url)

**Comment by trunghm** [comment]
Glad to know. So you can switch and use this native component rather than our custom one. Thanks

**Comment by ttawan** [comment]
@trunghm you're welcome. please merge it if you think it's okay. Thanks.

**Comment by trunghm** [comment]
All the mobile developers are on holidays now. let me merge it for now, if there's any issue, the developer can change it later. Thanks

**Pull request merged**
